[package]
name = "subpub"
version = "0.1.0"
edition = "2021"
description = "Automate the process of publishing crates from Substrate"

[dependencies]
anyhow = "1.0.55"
clap = { version = "3.1.2", features = ["derive"] }
toml = "0.5.8"
toml_edit = "0.13.4"
walkdir = "2.3.2"
