name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  reserve-crate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@55c7845fad90d0ae8b2e83715cb900e5e861e8cb # stable branch
        with:
          toolchain: stable

      # Put this AFTER installing Rust because the cache uses the current rustc
      # version as its cache key
      - name: Cache Rust
        uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6 # v2.2.0
        with:
          cache-on-failure: "true"

      - name: Install cargo-generate
        run: cargo install just --version 1.13.0

      - name: Check the code
        run: just all-checks
